<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>

        <PackageReference Include="xunit.v3.extensibility.core"/>
        <PackageReference Include="xunit.v3.assert"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\SegregatedStorage\SegregatedStorage.csproj"/>
    </ItemGroup>


</Project>
