<Project>
    <PropertyGroup>
        <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup Label="Pins">
        <PackageVersion Include="Microsoft.OpenApi" Version="2.12.0"/>
        <PackageVersion Include="SSH.NET" Version="2026.0.0"/>
    </ItemGroup>
    <ItemGroup Label="Cosmos">
        <PackageVersion Include="Microsoft.Azure.Cosmos" Version="3.62.1"/>
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.4"/>
    </ItemGroup>
    <ItemGroup Label="Mongo">
        <PackageVersion Include="MongoDB.Driver" Version="3.11.0"/>
    </ItemGroup>
    <ItemGroup Label="Azure">
        <PackageVersion Include="Azure.Storage.Blobs" Version="12.29.1"/>
    </ItemGroup>
    <ItemGroup Label="Main">
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10"/>
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10"/>
        <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10"/>
    </ItemGroup>
    <ItemGroup Label="API">
        <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3"/>
    </ItemGroup>
    <ItemGroup Label="Tests">
        <PackageVersion Include="coverlet.collector" Version="10.0.1"/>
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1"/>
        <PackageVersion Include="Testcontainers.CosmosDb" Version="4.13.0"/>
        <PackageVersion Include="Testcontainers.MongoDb" Version="4.13.0"/>
        <PackageVersion Include="Testcontainers.Azurite" Version="4.13.0"/>
        <PackageVersion Include="xunit" Version="2.9.3"/>
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5"/>
        <PackageVersion Include="NSubstitute" Version="6.1.0"/>
    </ItemGroup>
</Project>