<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>

        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Testcontainers.CosmosDb"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\FileRepositories\SegregatedStorage.CosmosFileRepository\SegregatedStorage.CosmosFileRepository.csproj"/>
        <ProjectReference Include="..\SegregatedStorage.FileRepository.IntegrationTests\SegregatedStorage.FileRepository.IntegrationTests.csproj"/>
    </ItemGroup>

</Project>
