<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
        <PackageReference Include="Newtonsoft.Json"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SegregatedStorage.AspNetCore\SegregatedStorage.AspNetCore.csproj"/>
        <ProjectReference Include="..\..\src\SegregatedStorage\SegregatedStorage.csproj"/>
    </ItemGroup>

</Project>
